/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class wrapper_FasttextWrapper */

#ifndef _Included_wrapper_FasttextWrapper
#define _Included_wrapper_FasttextWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wrapper_FasttextWrapper
 * Method:    train
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_wrapper_FasttextWrapper_train
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     wrapper_FasttextWrapper
 * Method:    loadModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_wrapper_FasttextWrapper_loadModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     wrapper_FasttextWrapper
 * Method:    unloadModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_wrapper_FasttextWrapper_unloadModel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     wrapper_FasttextWrapper
 * Method:    predict
 * Signature: (JLjava/lang/String;IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wrapper_FasttextWrapper_predict
  (JNIEnv *, jobject, jlong, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
